### ISSUE TITLE
PipelineClient.hincrbyfloat crashes

### ISSUE THREAD

**Issue by bmironenko** [debasishg/scala-redis#144] opened 2015-07-15 21:43 UTC
Executing hincrbyfloat inside a pipeline produces the following exception:

```
info]   java.lang.NullPointerException:
[info]   at com.redis.HashOperations$class.hincrbyfloat(HashOperations.scala:32)
[info]   at com.redis.RedisClient$PipelineClient.hincrbyfloat(RedisClient.scala:172)
[info]   at com.redis.PipelineSpec$$anonfun$11$$anonfun$apply$mcV$sp$9$$anonfun$21.apply(PipelineSpec.scala:150)
[info]   at com.redis.PipelineSpec$$anonfun$11$$anonfun$apply$mcV$sp$9$$anonfun$21.apply(PipelineSpec.scala:149)
[info]   at com.redis.RedisClient.pipeline(RedisClient.scala:108)
[info]   at com.redis.PipelineSpec$$anonfun$11$$anonfun$apply$mcV$sp$9.apply$mcV$sp(PipelineSpec.scala:149)
[info]   at com.redis.PipelineSpec$$anonfun$11$$anonfun$apply$mcV$sp$9.apply(PipelineSpec.scala:148)
[info]   at com.redis.PipelineSpec$$anonfun$11$$anonfun$apply$mcV$sp$9.apply(PipelineSpec.scala:148)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
```

**Comment by mogproject** [comment] 2015-09-30 03:22
:+1: 
I've found the same problem happens in `incrbyfloat` in StringOperations.
https://github.com/debasishg/scala-redis/blob/master/src/main/scala/com/redis/StringOperations.scala#L65

**Comment by debasishg** [comment] 2015-09-30 06:26
Thanks for reporting .. will take a look shortly ..

**Comment by dantodor** [comment] 2016-08-31 08:16
The issue is exactly the same with incrbyfloat, and the solution is the same as in the commit pushed by bmironenko to hincrbyfloat, i.e. the line 
`send("INCRBYFLOAT", List(key, increment))(asBulk).map(_.toFloat)`
should be 
`send("INCRBYFLOAT", List(key, increment))(asBulk.map(_.toFloat))`

**Comment by debasishg** [comment] 2016-08-31 11:19
Yes, I guess that's now fixed by https://github.com/debasishg/scala-redis/commit/7a0e2958e3c20b64eb2932bd26a7d522010bec40

**Comment by dantodor** [comment] 2016-09-01 02:37
The hincrbyfloat is fixed indeed, but incrbyfloat is not. It will behave the same when called in a pipeline.

**Comment by debasishg** [comment] 2016-09-01 04:19
ah .. I see .. I will fix it soon .. Thanks ..

**Comment by debasishg** [comment] 2016-09-01 11:54
Closing this issue and created https://github.com/debasishg/scala-redis/issues/176 for `incrbyfloat`

**Closed by debasishg** 2016-09-01 11:54 UTC
